<?php
  class Common_member_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_uid;  		 public $_email; 		 public $_username; 		 public $_password; 		 public $_status; 		 public $_emailstatus; 		 public $_avatarstatus; 		 public $_videophotostatus; 		 public $_adminid; 		 public $_groupid; 		 public $_groupexpiry; 		 public $_extgroupids; 		 public $_regdate; 		 public $_credits; 		 public $_notifysound; 		 public $_timeoffset; 		 public $_newpm; 		 public $_newprompt; 		 public $_accessmasks; 		 public $_allowadmincp; 		 public $_onlyacceptfriendpm; 		 public $_conisbind; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  common_member_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."n_member";		 }	    
	    		public function getUid(){			 return $this->_uid ;		}		public function getEmail(){			 return $this->_email ;		}		public function getUsername(){			 return $this->_username ;		}		public function getPassword(){			 return $this->_password ;		}		public function getStatus(){			 return $this->_status ;		}		public function getEmailstatus(){			 return $this->_emailstatus ;		}		public function getAvatarstatus(){			 return $this->_avatarstatus ;		}		public function getVideophotostatus(){			 return $this->_videophotostatus ;		}		public function getAdminid(){			 return $this->_adminid ;		}		public function getGroupid(){			 return $this->_groupid ;		}		public function getGroupexpiry(){			 return $this->_groupexpiry ;		}		public function getExtgroupids(){			 return $this->_extgroupids ;		}		public function getRegdate(){			 return $this->_regdate ;		}		public function getCredits(){			 return $this->_credits ;		}		public function getNotifysound(){			 return $this->_notifysound ;		}		public function getTimeoffset(){			 return $this->_timeoffset ;		}		public function getNewpm(){			 return $this->_newpm ;		}		public function getNewprompt(){			 return $this->_newprompt ;		}		public function getAccessmasks(){			 return $this->_accessmasks ;		}		public function getAllowadmincp(){			 return $this->_allowadmincp ;		}		public function getOnlyacceptfriendpm(){			 return $this->_onlyacceptfriendpm ;		}		public function getConisbind(){			 return $this->_conisbind ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setUid($value){ 			 $this->_uid = $value;		}		public function setEmail($value){ 			 $this->_email = $value;		}		public function setUsername($value){ 			 $this->_username = $value;		}		public function setPassword($value){ 			 $this->_password = $value;		}		public function setStatus($value){ 			 $this->_status = $value;		}		public function setEmailstatus($value){ 			 $this->_emailstatus = $value;		}		public function setAvatarstatus($value){ 			 $this->_avatarstatus = $value;		}		public function setVideophotostatus($value){ 			 $this->_videophotostatus = $value;		}		public function setAdminid($value){ 			 $this->_adminid = $value;		}		public function setGroupid($value){ 			 $this->_groupid = $value;		}		public function setGroupexpiry($value){ 			 $this->_groupexpiry = $value;		}		public function setExtgroupids($value){ 			 $this->_extgroupids = $value;		}		public function setRegdate($value){ 			 $this->_regdate = $value;		}		public function setCredits($value){ 			 $this->_credits = $value;		}		public function setNotifysound($value){ 			 $this->_notifysound = $value;		}		public function setTimeoffset($value){ 			 $this->_timeoffset = $value;		}		public function setNewpm($value){ 			 $this->_newpm = $value;		}		public function setNewprompt($value){ 			 $this->_newprompt = $value;		}		public function setAccessmasks($value){ 			 $this->_accessmasks = $value;		}		public function setAllowadmincp($value){ 			 $this->_allowadmincp = $value;		}		public function setOnlyacceptfriendpm($value){ 			 $this->_onlyacceptfriendpm = $value;		}		public function setConisbind($value){ 			 $this->_conisbind = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  common_member  ,or add new record		 * @return int last_insert_id		 */		function create_common_member(){		 		 $data =  array(); 					if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_email)){ 				 $data['email']=$this->_email;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_password)){ 				 $data['password']=$this->_password;			}			if(!is_null($this->_status)){ 				 $data['status']=$this->_status;			}			if(!is_null($this->_emailstatus)){ 				 $data['emailstatus']=$this->_emailstatus;			}			if(!is_null($this->_avatarstatus)){ 				 $data['avatarstatus']=$this->_avatarstatus;			}			if(!is_null($this->_videophotostatus)){ 				 $data['videophotostatus']=$this->_videophotostatus;			}			if(!is_null($this->_adminid)){ 				 $data['adminid']=$this->_adminid;			}			if(!is_null($this->_groupid)){ 				 $data['groupid']=$this->_groupid;			}			if(!is_null($this->_groupexpiry)){ 				 $data['groupexpiry']=$this->_groupexpiry;			}			if(!is_null($this->_extgroupids)){ 				 $data['extgroupids']=$this->_extgroupids;			}			if(!is_null($this->_regdate)){ 				 $data['regdate']=$this->_regdate;			}			if(!is_null($this->_credits)){ 				 $data['credits']=$this->_credits;			}			if(!is_null($this->_notifysound)){ 				 $data['notifysound']=$this->_notifysound;			}			if(!is_null($this->_timeoffset)){ 				 $data['timeoffset']=$this->_timeoffset;			}			if(!is_null($this->_newpm)){ 				 $data['newpm']=$this->_newpm;			}			if(!is_null($this->_newprompt)){ 				 $data['newprompt']=$this->_newprompt;			}			if(!is_null($this->_accessmasks)){ 				 $data['accessmasks']=$this->_accessmasks;			}			if(!is_null($this->_allowadmincp)){ 				 $data['allowadmincp']=$this->_allowadmincp;			}			if(!is_null($this->_onlyacceptfriendpm)){ 				 $data['onlyacceptfriendpm']=$this->_onlyacceptfriendpm;			}			if(!is_null($this->_conisbind)){ 				 $data['conisbind']=$this->_conisbind;			}			 return $this->_uid = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table common_member		 * @return int affected_rows		 */		function edit_common_member(){ 		 		 $data =  array();  					if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_email)){ 				 $data['email']=$this->_email;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_password)){ 				 $data['password']=$this->_password;			}			if(!is_null($this->_status)){ 				 $data['status']=$this->_status;			}			if(!is_null($this->_emailstatus)){ 				 $data['emailstatus']=$this->_emailstatus;			}			if(!is_null($this->_avatarstatus)){ 				 $data['avatarstatus']=$this->_avatarstatus;			}			if(!is_null($this->_videophotostatus)){ 				 $data['videophotostatus']=$this->_videophotostatus;			}			if(!is_null($this->_adminid)){ 				 $data['adminid']=$this->_adminid;			}			if(!is_null($this->_groupid)){ 				 $data['groupid']=$this->_groupid;			}			if(!is_null($this->_groupexpiry)){ 				 $data['groupexpiry']=$this->_groupexpiry;			}			if(!is_null($this->_extgroupids)){ 				 $data['extgroupids']=$this->_extgroupids;			}			if(!is_null($this->_regdate)){ 				 $data['regdate']=$this->_regdate;			}			if(!is_null($this->_credits)){ 				 $data['credits']=$this->_credits;			}			if(!is_null($this->_notifysound)){ 				 $data['notifysound']=$this->_notifysound;			}			if(!is_null($this->_timeoffset)){ 				 $data['timeoffset']=$this->_timeoffset;			}			if(!is_null($this->_newpm)){ 				 $data['newpm']=$this->_newpm;			}			if(!is_null($this->_newprompt)){ 				 $data['newprompt']=$this->_newprompt;			}			if(!is_null($this->_accessmasks)){ 				 $data['accessmasks']=$this->_accessmasks;			}			if(!is_null($this->_allowadmincp)){ 				 $data['allowadmincp']=$this->_allowadmincp;			}			if(!is_null($this->_onlyacceptfriendpm)){ 				 $data['onlyacceptfriendpm']=$this->_onlyacceptfriendpm;			}			if(!is_null($this->_conisbind)){ 				 $data['conisbind']=$this->_conisbind;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('uid' => $this->_uid); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: common_member,if isset where return where record,else return all record		 * @return array 		 */		function query_common_member($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count common_member records,if iset where query by where 		 * @return int count records		 */		function count_common_member(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table common_member, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_common_member(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where uid = $this->_uid "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>