<?php
  class Keke_witkey_studio_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_studio_id;  		 public $_title; 		 public $_aboutus; 		 public $_logo; 		 public $_members; 		 public $_banner_pic; 		 public $_uid; 		 public $_address; 		 public $_postcode; 		 public $_email; 		 public $_phone; 		 public $_fax; 		 public $_area; 		 public $_username; 		 public $_studio_status; 		 public $_on_date; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_studio_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."itkey_studio";		 }	    
	    		public function getStudio_id(){			 return $this->_studio_id ;		}		public function getTitle(){			 return $this->_title ;		}		public function getAboutus(){			 return $this->_aboutus ;		}		public function getLogo(){			 return $this->_logo ;		}		public function getMembers(){			 return $this->_members ;		}		public function getBanner_pic(){			 return $this->_banner_pic ;		}		public function getUid(){			 return $this->_uid ;		}		public function getAddress(){			 return $this->_address ;		}		public function getPostcode(){			 return $this->_postcode ;		}		public function getEmail(){			 return $this->_email ;		}		public function getPhone(){			 return $this->_phone ;		}		public function getFax(){			 return $this->_fax ;		}		public function getArea(){			 return $this->_area ;		}		public function getUsername(){			 return $this->_username ;		}		public function getStudio_status(){			 return $this->_studio_status ;		}		public function getOn_date(){			 return $this->_on_date ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setStudio_id($value){ 			 $this->_studio_id = $value;		}		public function setTitle($value){ 			 $this->_title = $value;		}		public function setAboutus($value){ 			 $this->_aboutus = $value;		}		public function setLogo($value){ 			 $this->_logo = $value;		}		public function setMembers($value){ 			 $this->_members = $value;		}		public function setBanner_pic($value){ 			 $this->_banner_pic = $value;		}		public function setUid($value){ 			 $this->_uid = $value;		}		public function setAddress($value){ 			 $this->_address = $value;		}		public function setPostcode($value){ 			 $this->_postcode = $value;		}		public function setEmail($value){ 			 $this->_email = $value;		}		public function setPhone($value){ 			 $this->_phone = $value;		}		public function setFax($value){ 			 $this->_fax = $value;		}		public function setArea($value){ 			 $this->_area = $value;		}		public function setUsername($value){ 			 $this->_username = $value;		}		public function setStudio_status($value){ 			 $this->_studio_status = $value;		}		public function setOn_date($value){ 			 $this->_on_date = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_studio  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_studio(){		 		 $data =  array(); 					if(!is_null($this->_studio_id)){ 				 $data['studio_id']=$this->_studio_id;			}			if(!is_null($this->_title)){ 				 $data['title']=$this->_title;			}			if(!is_null($this->_aboutus)){ 				 $data['aboutus']=$this->_aboutus;			}			if(!is_null($this->_logo)){ 				 $data['logo']=$this->_logo;			}			if(!is_null($this->_members)){ 				 $data['members']=$this->_members;			}			if(!is_null($this->_banner_pic)){ 				 $data['banner_pic']=$this->_banner_pic;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_address)){ 				 $data['address']=$this->_address;			}			if(!is_null($this->_postcode)){ 				 $data['postcode']=$this->_postcode;			}			if(!is_null($this->_email)){ 				 $data['email']=$this->_email;			}			if(!is_null($this->_phone)){ 				 $data['phone']=$this->_phone;			}			if(!is_null($this->_fax)){ 				 $data['fax']=$this->_fax;			}			if(!is_null($this->_area)){ 				 $data['area']=$this->_area;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_studio_status)){ 				 $data['studio_status']=$this->_studio_status;			}			if(!is_null($this->_on_date)){ 				 $data['on_date']=$this->_on_date;			}			 return $this->_studio_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_studio		 * @return int affected_rows		 */		function edit_keke_witkey_studio(){ 		 		 $data =  array();  					if(!is_null($this->_studio_id)){ 				 $data['studio_id']=$this->_studio_id;			}			if(!is_null($this->_title)){ 				 $data['title']=$this->_title;			}			if(!is_null($this->_aboutus)){ 				 $data['aboutus']=$this->_aboutus;			}			if(!is_null($this->_logo)){ 				 $data['logo']=$this->_logo;			}			if(!is_null($this->_members)){ 				 $data['members']=$this->_members;			}			if(!is_null($this->_banner_pic)){ 				 $data['banner_pic']=$this->_banner_pic;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_address)){ 				 $data['address']=$this->_address;			}			if(!is_null($this->_postcode)){ 				 $data['postcode']=$this->_postcode;			}			if(!is_null($this->_email)){ 				 $data['email']=$this->_email;			}			if(!is_null($this->_phone)){ 				 $data['phone']=$this->_phone;			}			if(!is_null($this->_fax)){ 				 $data['fax']=$this->_fax;			}			if(!is_null($this->_area)){ 				 $data['area']=$this->_area;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_studio_status)){ 				 $data['studio_status']=$this->_studio_status;			}			if(!is_null($this->_on_date)){ 				 $data['on_date']=$this->_on_date;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('studio_id' => $this->_studio_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_studio,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_studio($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_studio records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_studio(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_studio, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_studio(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where studio_id = $this->_studio_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>