<?php
  class Keke_witkey_mark_log_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_mark_id;  		 public $_obj; 		 public $_obj_id; 		 public $_mark_status; 		 public $_mark_content; 		 public $_mark_time; 		 public $_uid; 		 public $_username; 		 public $_mark_max_time; 		 public $_by_uid; 		 public $_by_username; 		 public $_user_type; 		 public $_obj_cash; 		 public $_work_id; 		 public $_mark_type; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_mark_log_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."itkey_mark_log";		 }	    
	    		public function getMark_id(){			 return $this->_mark_id ;		}		public function getObj(){			 return $this->_obj ;		}		public function getObj_id(){			 return $this->_obj_id ;		}		public function getMark_status(){			 return $this->_mark_status ;		}		public function getMark_content(){			 return $this->_mark_content ;		}		public function getMark_time(){			 return $this->_mark_time ;		}		public function getUid(){			 return $this->_uid ;		}		public function getUsername(){			 return $this->_username ;		}		public function getMark_max_time(){			 return $this->_mark_max_time ;		}		public function getBy_uid(){			 return $this->_by_uid ;		}		public function getBy_username(){			 return $this->_by_username ;		}		public function getUser_type(){			 return $this->_user_type ;		}		public function getObj_cash(){			 return $this->_obj_cash ;		}		public function getWork_id(){			 return $this->_work_id ;		}		public function getMark_type(){			 return $this->_mark_type ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setMark_id($value){ 			 $this->_mark_id = $value;		}		public function setObj($value){ 			 $this->_obj = $value;		}		public function setObj_id($value){ 			 $this->_obj_id = $value;		}		public function setMark_status($value){ 			 $this->_mark_status = $value;		}		public function setMark_content($value){ 			 $this->_mark_content = $value;		}		public function setMark_time($value){ 			 $this->_mark_time = $value;		}		public function setUid($value){ 			 $this->_uid = $value;		}		public function setUsername($value){ 			 $this->_username = $value;		}		public function setMark_max_time($value){ 			 $this->_mark_max_time = $value;		}		public function setBy_uid($value){ 			 $this->_by_uid = $value;		}		public function setBy_username($value){ 			 $this->_by_username = $value;		}		public function setUser_type($value){ 			 $this->_user_type = $value;		}		public function setObj_cash($value){ 			 $this->_obj_cash = $value;		}		public function setWork_id($value){ 			 $this->_work_id = $value;		}		public function setMark_type($value){ 			 $this->_mark_type = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_mark_log  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_mark_log(){		 		 $data =  array(); 					if(!is_null($this->_mark_id)){ 				 $data['mark_id']=$this->_mark_id;			}			if(!is_null($this->_obj)){ 				 $data['obj']=$this->_obj;			}			if(!is_null($this->_obj_id)){ 				 $data['obj_id']=$this->_obj_id;			}			if(!is_null($this->_mark_status)){ 				 $data['mark_status']=$this->_mark_status;			}			if(!is_null($this->_mark_content)){ 				 $data['mark_content']=$this->_mark_content;			}			if(!is_null($this->_mark_time)){ 				 $data['mark_time']=$this->_mark_time;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_mark_max_time)){ 				 $data['mark_max_time']=$this->_mark_max_time;			}			if(!is_null($this->_by_uid)){ 				 $data['by_uid']=$this->_by_uid;			}			if(!is_null($this->_by_username)){ 				 $data['by_username']=$this->_by_username;			}			if(!is_null($this->_user_type)){ 				 $data['user_type']=$this->_user_type;			}			if(!is_null($this->_obj_cash)){ 				 $data['obj_cash']=$this->_obj_cash;			}			if(!is_null($this->_work_id)){ 				 $data['work_id']=$this->_work_id;			}			if(!is_null($this->_mark_type)){ 				 $data['mark_type']=$this->_mark_type;			}			 return $this->_mark_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_mark_log		 * @return int affected_rows		 */		function edit_keke_witkey_mark_log(){ 		 		 $data =  array();  					if(!is_null($this->_mark_id)){ 				 $data['mark_id']=$this->_mark_id;			}			if(!is_null($this->_obj)){ 				 $data['obj']=$this->_obj;			}			if(!is_null($this->_obj_id)){ 				 $data['obj_id']=$this->_obj_id;			}			if(!is_null($this->_mark_status)){ 				 $data['mark_status']=$this->_mark_status;			}			if(!is_null($this->_mark_content)){ 				 $data['mark_content']=$this->_mark_content;			}			if(!is_null($this->_mark_time)){ 				 $data['mark_time']=$this->_mark_time;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_mark_max_time)){ 				 $data['mark_max_time']=$this->_mark_max_time;			}			if(!is_null($this->_by_uid)){ 				 $data['by_uid']=$this->_by_uid;			}			if(!is_null($this->_by_username)){ 				 $data['by_username']=$this->_by_username;			}			if(!is_null($this->_user_type)){ 				 $data['user_type']=$this->_user_type;			}			if(!is_null($this->_obj_cash)){ 				 $data['obj_cash']=$this->_obj_cash;			}			if(!is_null($this->_work_id)){ 				 $data['work_id']=$this->_work_id;			}			if(!is_null($this->_mark_type)){ 				 $data['mark_type']=$this->_mark_type;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('mark_id' => $this->_mark_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_mark_log,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_mark_log($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_mark_log records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_mark_log(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_mark_log, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_mark_log(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where mark_id = $this->_mark_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>