<?php
  class Keke_witkey_coper_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_coper_id;  		 public $_brand; 		 public $_name; 		 public $_email; 		 public $_mobile; 		 public $_telephone; 		 public $_qq; 		 public $_region; 		 public $_address; 		 public $_type; 		 public $_description; 		 public $_status; 		 public $_on_time; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_coper_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_coper";		 }	    
	    		public function getCoper_id(){			 return $this->_coper_id ;		}		public function getBrand(){			 return $this->_brand ;		}		public function getName(){			 return $this->_name ;		}		public function getEmail(){			 return $this->_email ;		}		public function getMobile(){			 return $this->_mobile ;		}		public function getTelephone(){			 return $this->_telephone ;		}		public function getQq(){			 return $this->_qq ;		}		public function getRegion(){			 return $this->_region ;		}		public function getAddress(){			 return $this->_address ;		}		public function getType(){			 return $this->_type ;		}		public function getDescription(){			 return $this->_description ;		}		public function getStatus(){			 return $this->_status ;		}		public function getOn_time(){			 return $this->_on_time ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setCoper_id($value){ 			 $this->_coper_id = $value;		}		public function setBrand($value){ 			 $this->_brand = $value;		}		public function setName($value){ 			 $this->_name = $value;		}		public function setEmail($value){ 			 $this->_email = $value;		}		public function setMobile($value){ 			 $this->_mobile = $value;		}		public function setTelephone($value){ 			 $this->_telephone = $value;		}		public function setQq($value){ 			 $this->_qq = $value;		}		public function setRegion($value){ 			 $this->_region = $value;		}		public function setAddress($value){ 			 $this->_address = $value;		}		public function setType($value){ 			 $this->_type = $value;		}		public function setDescription($value){ 			 $this->_description = $value;		}		public function setStatus($value){ 			 $this->_status = $value;		}		public function setOn_time($value){ 			 $this->_on_time = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_coper  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_coper(){		 		 $data =  array(); 					if(!is_null($this->_coper_id)){ 				 $data['coper_id']=$this->_coper_id;			}			if(!is_null($this->_brand)){ 				 $data['brand']=$this->_brand;			}			if(!is_null($this->_name)){ 				 $data['name']=$this->_name;			}			if(!is_null($this->_email)){ 				 $data['email']=$this->_email;			}			if(!is_null($this->_mobile)){ 				 $data['mobile']=$this->_mobile;			}			if(!is_null($this->_telephone)){ 				 $data['telephone']=$this->_telephone;			}			if(!is_null($this->_qq)){ 				 $data['qq']=$this->_qq;			}			if(!is_null($this->_region)){ 				 $data['region']=$this->_region;			}			if(!is_null($this->_address)){ 				 $data['address']=$this->_address;			}			if(!is_null($this->_type)){ 				 $data['type']=$this->_type;			}			if(!is_null($this->_description)){ 				 $data['description']=$this->_description;			}			if(!is_null($this->_status)){ 				 $data['status']=$this->_status;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			 return $this->_coper_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_coper		 * @return int affected_rows		 */		function edit_keke_witkey_coper(){ 		 		 $data =  array();  					if(!is_null($this->_coper_id)){ 				 $data['coper_id']=$this->_coper_id;			}			if(!is_null($this->_brand)){ 				 $data['brand']=$this->_brand;			}			if(!is_null($this->_name)){ 				 $data['name']=$this->_name;			}			if(!is_null($this->_email)){ 				 $data['email']=$this->_email;			}			if(!is_null($this->_mobile)){ 				 $data['mobile']=$this->_mobile;			}			if(!is_null($this->_telephone)){ 				 $data['telephone']=$this->_telephone;			}			if(!is_null($this->_qq)){ 				 $data['qq']=$this->_qq;			}			if(!is_null($this->_region)){ 				 $data['region']=$this->_region;			}			if(!is_null($this->_address)){ 				 $data['address']=$this->_address;			}			if(!is_null($this->_type)){ 				 $data['type']=$this->_type;			}			if(!is_null($this->_description)){ 				 $data['description']=$this->_description;			}			if(!is_null($this->_status)){ 				 $data['status']=$this->_status;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('coper_id' => $this->_coper_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_coper,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_coper($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_coper records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_coper(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    		function del_keke_witkey_coper(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where coper_id = $this->_coper_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>