<?php
  class Keke_witkey_paypal_config_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_paypay_config_id;  		 public $_currency; 		 public $_recharge_min; 		 public $_withdraw_min; 		 public $_withdraw_max; 		 public $_alipay_num; 		 public $_alipay_partner; 		 public $_alipay_safety_code; 		 public $_tenpay_seller_id; 		 public $_tenpay_ckey; 		 public $_chinabank_seller_id; 		 public $_chinabank_ckey; 		 public $_on_time; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_paypal_config_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."itkey_paypal_config";		 }	    
	    		public function getPaypay_config_id(){			 return $this->_paypay_config_id ;		}		public function getCurrency(){			 return $this->_currency ;		}		public function getRecharge_min(){			 return $this->_recharge_min ;		}		public function getWithdraw_min(){			 return $this->_withdraw_min ;		}		public function getWithdraw_max(){			 return $this->_withdraw_max ;		}		public function getAlipay_num(){			 return $this->_alipay_num ;		}		public function getAlipay_partner(){			 return $this->_alipay_partner ;		}		public function getAlipay_safety_code(){			 return $this->_alipay_safety_code ;		}		public function getTenpay_seller_id(){			 return $this->_tenpay_seller_id ;		}		public function getTenpay_ckey(){			 return $this->_tenpay_ckey ;		}		public function getChinabank_seller_id(){			 return $this->_chinabank_seller_id ;		}		public function getChinabank_ckey(){			 return $this->_chinabank_ckey ;		}		public function getOn_time(){			 return $this->_on_time ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setPaypay_config_id($value){ 			 $this->_paypay_config_id = $value;		}		public function setCurrency($value){ 			 $this->_currency = $value;		}		public function setRecharge_min($value){ 			 $this->_recharge_min = $value;		}		public function setWithdraw_min($value){ 			 $this->_withdraw_min = $value;		}		public function setWithdraw_max($value){ 			 $this->_withdraw_max = $value;		}		public function setAlipay_num($value){ 			 $this->_alipay_num = $value;		}		public function setAlipay_partner($value){ 			 $this->_alipay_partner = $value;		}		public function setAlipay_safety_code($value){ 			 $this->_alipay_safety_code = $value;		}		public function setTenpay_seller_id($value){ 			 $this->_tenpay_seller_id = $value;		}		public function setTenpay_ckey($value){ 			 $this->_tenpay_ckey = $value;		}		public function setChinabank_seller_id($value){ 			 $this->_chinabank_seller_id = $value;		}		public function setChinabank_ckey($value){ 			 $this->_chinabank_ckey = $value;		}		public function setOn_time($value){ 			 $this->_on_time = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_paypal_config  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_paypal_config(){		 		 $data =  array(); 					if(!is_null($this->_paypay_config_id)){ 				 $data['paypay_config_id']=$this->_paypay_config_id;			}			if(!is_null($this->_currency)){ 				 $data['currency']=$this->_currency;			}			if(!is_null($this->_recharge_min)){ 				 $data['recharge_min']=$this->_recharge_min;			}			if(!is_null($this->_withdraw_min)){ 				 $data['withdraw_min']=$this->_withdraw_min;			}			if(!is_null($this->_withdraw_max)){ 				 $data['withdraw_max']=$this->_withdraw_max;			}			if(!is_null($this->_alipay_num)){ 				 $data['alipay_num']=$this->_alipay_num;			}			if(!is_null($this->_alipay_partner)){ 				 $data['alipay_partner']=$this->_alipay_partner;			}			if(!is_null($this->_alipay_safety_code)){ 				 $data['alipay_safety_code']=$this->_alipay_safety_code;			}			if(!is_null($this->_tenpay_seller_id)){ 				 $data['tenpay_seller_id']=$this->_tenpay_seller_id;			}			if(!is_null($this->_tenpay_ckey)){ 				 $data['tenpay_ckey']=$this->_tenpay_ckey;			}			if(!is_null($this->_chinabank_seller_id)){ 				 $data['chinabank_seller_id']=$this->_chinabank_seller_id;			}			if(!is_null($this->_chinabank_ckey)){ 				 $data['chinabank_ckey']=$this->_chinabank_ckey;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			 return $this->_paypay_config_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_paypal_config		 * @return int affected_rows		 */		function edit_keke_witkey_paypal_config(){ 		 		 $data =  array();  					if(!is_null($this->_paypay_config_id)){ 				 $data['paypay_config_id']=$this->_paypay_config_id;			}			if(!is_null($this->_currency)){ 				 $data['currency']=$this->_currency;			}			if(!is_null($this->_recharge_min)){ 				 $data['recharge_min']=$this->_recharge_min;			}			if(!is_null($this->_withdraw_min)){ 				 $data['withdraw_min']=$this->_withdraw_min;			}			if(!is_null($this->_withdraw_max)){ 				 $data['withdraw_max']=$this->_withdraw_max;			}			if(!is_null($this->_alipay_num)){ 				 $data['alipay_num']=$this->_alipay_num;			}			if(!is_null($this->_alipay_partner)){ 				 $data['alipay_partner']=$this->_alipay_partner;			}			if(!is_null($this->_alipay_safety_code)){ 				 $data['alipay_safety_code']=$this->_alipay_safety_code;			}			if(!is_null($this->_tenpay_seller_id)){ 				 $data['tenpay_seller_id']=$this->_tenpay_seller_id;			}			if(!is_null($this->_tenpay_ckey)){ 				 $data['tenpay_ckey']=$this->_tenpay_ckey;			}			if(!is_null($this->_chinabank_seller_id)){ 				 $data['chinabank_seller_id']=$this->_chinabank_seller_id;			}			if(!is_null($this->_chinabank_ckey)){ 				 $data['chinabank_ckey']=$this->_chinabank_ckey;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('paypay_config_id' => $this->_paypay_config_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_paypal_config,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_paypal_config($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_paypal_config records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_paypal_config(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_paypal_config, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_paypal_config(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where paypay_config_id = $this->_paypay_config_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>