<?php
  class Keke_witkey_shop_topimg_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_topimg_id;  		 public $_shop_id; 		 public $_uid; 		 public $_username; 		 public $_ban_1; 		 public $_ban_2; 		 public $_ban_3; 		 public $_ban_4; 		 public $_ban_5; 		 public $_ban_6; 		 public $_on_time; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_shop_topimg_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_shop_topimg";		 }	    
	    		public function getTopimg_id(){			 return $this->_topimg_id ;		}		public function getShop_id(){			 return $this->_shop_id ;		}		public function getUid(){			 return $this->_uid ;		}		public function getUsername(){			 return $this->_username ;		}		public function getBan_1(){			 return $this->_ban_1 ;		}		public function getBan_2(){			 return $this->_ban_2 ;		}		public function getBan_3(){			 return $this->_ban_3 ;		}		public function getBan_4(){			 return $this->_ban_4 ;		}		public function getBan_5(){			 return $this->_ban_5 ;		}		public function getBan_6(){			 return $this->_ban_6 ;		}		public function getOn_time(){			 return $this->_on_time ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setTopimg_id($value){ 			 $this->_topimg_id = $value;		}		public function setShop_id($value){ 			 $this->_shop_id = $value;		}		public function setUid($value){ 			 $this->_uid = $value;		}		public function setUsername($value){ 			 $this->_username = $value;		}		public function setBan_1($value){ 			 $this->_ban_1 = $value;		}		public function setBan_2($value){ 			 $this->_ban_2 = $value;		}		public function setBan_3($value){ 			 $this->_ban_3 = $value;		}		public function setBan_4($value){ 			 $this->_ban_4 = $value;		}		public function setBan_5($value){ 			 $this->_ban_5 = $value;		}		public function setBan_6($value){ 			 $this->_ban_6 = $value;		}		public function setOn_time($value){ 			 $this->_on_time = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_shop_topimg  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_shop_topimg(){		 		 $data =  array(); 					if(!is_null($this->_topimg_id)){ 				 $data['topimg_id']=$this->_topimg_id;			}			if(!is_null($this->_shop_id)){ 				 $data['shop_id']=$this->_shop_id;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_ban_1)){ 				 $data['ban_1']=$this->_ban_1;			}			if(!is_null($this->_ban_2)){ 				 $data['ban_2']=$this->_ban_2;			}			if(!is_null($this->_ban_3)){ 				 $data['ban_3']=$this->_ban_3;			}			if(!is_null($this->_ban_4)){ 				 $data['ban_4']=$this->_ban_4;			}			if(!is_null($this->_ban_5)){ 				 $data['ban_5']=$this->_ban_5;			}			if(!is_null($this->_ban_6)){ 				 $data['ban_6']=$this->_ban_6;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			 return $this->_topimg_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_shop_topimg		 * @return int affected_rows		 */		function edit_keke_witkey_shop_topimg(){ 		 		 $data =  array();  					if(!is_null($this->_topimg_id)){ 				 $data['topimg_id']=$this->_topimg_id;			}			if(!is_null($this->_shop_id)){ 				 $data['shop_id']=$this->_shop_id;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_ban_1)){ 				 $data['ban_1']=$this->_ban_1;			}			if(!is_null($this->_ban_2)){ 				 $data['ban_2']=$this->_ban_2;			}			if(!is_null($this->_ban_3)){ 				 $data['ban_3']=$this->_ban_3;			}			if(!is_null($this->_ban_4)){ 				 $data['ban_4']=$this->_ban_4;			}			if(!is_null($this->_ban_5)){ 				 $data['ban_5']=$this->_ban_5;			}			if(!is_null($this->_ban_6)){ 				 $data['ban_6']=$this->_ban_6;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('topimg_id' => $this->_topimg_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_shop_topimg,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_shop_topimg($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_shop_topimg records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_shop_topimg(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_shop_topimg, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_shop_topimg(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where topimg_id = $this->_topimg_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>