<?php
  class Keke_witkey_score_config_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_login;  		 public $_register; 		 public $_update_pic; 		 public $_edit_userinfo; 		 public $_edit_withdrawinfo; 		 public $_buy_vip; 		 public $_online_pay; 		 public $_withdraw; 		 public $_pub_task; 		 public $_view_task; 		 public $_collect_task; 		 public $_task_comment; 		 public $_task_apply; 		 public $_task_pubwork; 		 public $_task_bid; 		 public $_work_accept; 		 public $_view_space; 		 public $_user_mark; 		 public $_access_shop; 		 public $_buy_service; 		 public $_create_service; 		 public $_service_comment; 		 public $_create_shop; 		 public $_update_date; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_score_config_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."itkey_score_config";		 }	    
	    		public function getLogin(){			 return $this->_login ;		}		public function getRegister(){			 return $this->_register ;		}		public function getUpdate_pic(){			 return $this->_update_pic ;		}		public function getEdit_userinfo(){			 return $this->_edit_userinfo ;		}		public function getEdit_withdrawinfo(){			 return $this->_edit_withdrawinfo ;		}		public function getBuy_vip(){			 return $this->_buy_vip ;		}		public function getOnline_pay(){			 return $this->_online_pay ;		}		public function getWithdraw(){			 return $this->_withdraw ;		}		public function getPub_task(){			 return $this->_pub_task ;		}		public function getView_task(){			 return $this->_view_task ;		}		public function getCollect_task(){			 return $this->_collect_task ;		}		public function getTask_comment(){			 return $this->_task_comment ;		}		public function getTask_apply(){			 return $this->_task_apply ;		}		public function getTask_pubwork(){			 return $this->_task_pubwork ;		}		public function getTask_bid(){			 return $this->_task_bid ;		}		public function getWork_accept(){			 return $this->_work_accept ;		}		public function getView_space(){			 return $this->_view_space ;		}		public function getUser_mark(){			 return $this->_user_mark ;		}		public function getAccess_shop(){			 return $this->_access_shop ;		}		public function getBuy_service(){			 return $this->_buy_service ;		}		public function getCreate_service(){			 return $this->_create_service ;		}		public function getService_comment(){			 return $this->_service_comment ;		}		public function getCreate_shop(){			 return $this->_create_shop ;		}		public function getUpdate_date(){			 return $this->_update_date ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setLogin($value){ 			 $this->_login = $value;		}		public function setRegister($value){ 			 $this->_register = $value;		}		public function setUpdate_pic($value){ 			 $this->_update_pic = $value;		}		public function setEdit_userinfo($value){ 			 $this->_edit_userinfo = $value;		}		public function setEdit_withdrawinfo($value){ 			 $this->_edit_withdrawinfo = $value;		}		public function setBuy_vip($value){ 			 $this->_buy_vip = $value;		}		public function setOnline_pay($value){ 			 $this->_online_pay = $value;		}		public function setWithdraw($value){ 			 $this->_withdraw = $value;		}		public function setPub_task($value){ 			 $this->_pub_task = $value;		}		public function setView_task($value){ 			 $this->_view_task = $value;		}		public function setCollect_task($value){ 			 $this->_collect_task = $value;		}		public function setTask_comment($value){ 			 $this->_task_comment = $value;		}		public function setTask_apply($value){ 			 $this->_task_apply = $value;		}		public function setTask_pubwork($value){ 			 $this->_task_pubwork = $value;		}		public function setTask_bid($value){ 			 $this->_task_bid = $value;		}		public function setWork_accept($value){ 			 $this->_work_accept = $value;		}		public function setView_space($value){ 			 $this->_view_space = $value;		}		public function setUser_mark($value){ 			 $this->_user_mark = $value;		}		public function setAccess_shop($value){ 			 $this->_access_shop = $value;		}		public function setBuy_service($value){ 			 $this->_buy_service = $value;		}		public function setCreate_service($value){ 			 $this->_create_service = $value;		}		public function setService_comment($value){ 			 $this->_service_comment = $value;		}		public function setCreate_shop($value){ 			 $this->_create_shop = $value;		}		public function setUpdate_date($value){ 			 $this->_update_date = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_score_config  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_score_config(){		 		 $data =  array(); 					if(!is_null($this->_login)){ 				 $data['login']=$this->_login;			}			if(!is_null($this->_register)){ 				 $data['register']=$this->_register;			}			if(!is_null($this->_update_pic)){ 				 $data['update_pic']=$this->_update_pic;			}			if(!is_null($this->_edit_userinfo)){ 				 $data['edit_userinfo']=$this->_edit_userinfo;			}			if(!is_null($this->_edit_withdrawinfo)){ 				 $data['edit_withdrawinfo']=$this->_edit_withdrawinfo;			}			if(!is_null($this->_buy_vip)){ 				 $data['buy_vip']=$this->_buy_vip;			}			if(!is_null($this->_online_pay)){ 				 $data['online_pay']=$this->_online_pay;			}			if(!is_null($this->_withdraw)){ 				 $data['withdraw']=$this->_withdraw;			}			if(!is_null($this->_pub_task)){ 				 $data['pub_task']=$this->_pub_task;			}			if(!is_null($this->_view_task)){ 				 $data['view_task']=$this->_view_task;			}			if(!is_null($this->_collect_task)){ 				 $data['collect_task']=$this->_collect_task;			}			if(!is_null($this->_task_comment)){ 				 $data['task_comment']=$this->_task_comment;			}			if(!is_null($this->_task_apply)){ 				 $data['task_apply']=$this->_task_apply;			}			if(!is_null($this->_task_pubwork)){ 				 $data['task_pubwork']=$this->_task_pubwork;			}			if(!is_null($this->_task_bid)){ 				 $data['task_bid']=$this->_task_bid;			}			if(!is_null($this->_work_accept)){ 				 $data['work_accept']=$this->_work_accept;			}			if(!is_null($this->_view_space)){ 				 $data['view_space']=$this->_view_space;			}			if(!is_null($this->_user_mark)){ 				 $data['user_mark']=$this->_user_mark;			}			if(!is_null($this->_access_shop)){ 				 $data['access_shop']=$this->_access_shop;			}			if(!is_null($this->_buy_service)){ 				 $data['buy_service']=$this->_buy_service;			}			if(!is_null($this->_create_service)){ 				 $data['create_service']=$this->_create_service;			}			if(!is_null($this->_service_comment)){ 				 $data['service_comment']=$this->_service_comment;			}			if(!is_null($this->_create_shop)){ 				 $data['create_shop']=$this->_create_shop;			}			if(!is_null($this->_update_date)){ 				 $data['update_date']=$this->_update_date;			}			 return $this->_login = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_score_config		 * @return int affected_rows		 */		function edit_keke_witkey_score_config(){ 		 		 $data =  array();  					if(!is_null($this->_login)){ 				 $data['login']=$this->_login;			}			if(!is_null($this->_register)){ 				 $data['register']=$this->_register;			}			if(!is_null($this->_update_pic)){ 				 $data['update_pic']=$this->_update_pic;			}			if(!is_null($this->_edit_userinfo)){ 				 $data['edit_userinfo']=$this->_edit_userinfo;			}			if(!is_null($this->_edit_withdrawinfo)){ 				 $data['edit_withdrawinfo']=$this->_edit_withdrawinfo;			}			if(!is_null($this->_buy_vip)){ 				 $data['buy_vip']=$this->_buy_vip;			}			if(!is_null($this->_online_pay)){ 				 $data['online_pay']=$this->_online_pay;			}			if(!is_null($this->_withdraw)){ 				 $data['withdraw']=$this->_withdraw;			}			if(!is_null($this->_pub_task)){ 				 $data['pub_task']=$this->_pub_task;			}			if(!is_null($this->_view_task)){ 				 $data['view_task']=$this->_view_task;			}			if(!is_null($this->_collect_task)){ 				 $data['collect_task']=$this->_collect_task;			}			if(!is_null($this->_task_comment)){ 				 $data['task_comment']=$this->_task_comment;			}			if(!is_null($this->_task_apply)){ 				 $data['task_apply']=$this->_task_apply;			}			if(!is_null($this->_task_pubwork)){ 				 $data['task_pubwork']=$this->_task_pubwork;			}			if(!is_null($this->_task_bid)){ 				 $data['task_bid']=$this->_task_bid;			}			if(!is_null($this->_work_accept)){ 				 $data['work_accept']=$this->_work_accept;			}			if(!is_null($this->_view_space)){ 				 $data['view_space']=$this->_view_space;			}			if(!is_null($this->_user_mark)){ 				 $data['user_mark']=$this->_user_mark;			}			if(!is_null($this->_access_shop)){ 				 $data['access_shop']=$this->_access_shop;			}			if(!is_null($this->_buy_service)){ 				 $data['buy_service']=$this->_buy_service;			}			if(!is_null($this->_create_service)){ 				 $data['create_service']=$this->_create_service;			}			if(!is_null($this->_service_comment)){ 				 $data['service_comment']=$this->_service_comment;			}			if(!is_null($this->_create_shop)){ 				 $data['create_shop']=$this->_create_shop;			}			if(!is_null($this->_update_date)){ 				 $data['update_date']=$this->_update_date;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('login' => $this->_login); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_score_config,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_score_config($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_score_config records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_score_config(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_score_config, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_score_config(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where login = $this->_login "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>