<?php
  class Keke_witkey_service_order_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_order_id;  		 public $_model_id; 		 public $_sale_uid; 		 public $_sale_username; 		 public $_service_id; 		 public $_service_type; 		 public $_on_time; 		 public $_count_cash; 		 public $_pay_cash; 		 public $_clr_cash; 		 public $_title; 		 public $_sale_status; 		 public $_buyer_status; 		 public $_order_status; 		 public $_buy_username; 		 public $_buy_uid; 		 public $_cost_cash; 		 public $_cost_credit; 		 public $_order_num; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_service_order_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_service_order";		 }	    
	    		public function getOrder_id(){			 return $this->_order_id ;		}		public function getModel_id(){			 return $this->_model_id ;		}		public function getSale_uid(){			 return $this->_sale_uid ;		}		public function getSale_username(){			 return $this->_sale_username ;		}		public function getService_id(){			 return $this->_service_id ;		}		public function getService_type(){			 return $this->_service_type ;		}		public function getOn_time(){			 return $this->_on_time ;		}		public function getCount_cash(){			 return $this->_count_cash ;		}		public function getPay_cash(){			 return $this->_pay_cash ;		}		public function getClr_cash(){			 return $this->_clr_cash ;		}		public function getTitle(){			 return $this->_title ;		}		public function getSale_status(){			 return $this->_sale_status ;		}		public function getBuyer_status(){			 return $this->_buyer_status ;		}		public function getOrder_status(){			 return $this->_order_status ;		}		public function getBuy_username(){			 return $this->_buy_username ;		}		public function getBuy_uid(){			 return $this->_buy_uid ;		}		public function getCost_cash(){			 return $this->_cost_cash ;		}		public function getCost_credit(){			 return $this->_cost_credit ;		}		public function getOrder_num(){			 return $this->_order_num ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setOrder_id($value){ 			 $this->_order_id = $value;		}		public function setModel_id($value){ 			 $this->_model_id = $value;		}		public function setSale_uid($value){ 			 $this->_sale_uid = $value;		}		public function setSale_username($value){ 			 $this->_sale_username = $value;		}		public function setService_id($value){ 			 $this->_service_id = $value;		}		public function setService_type($value){ 			 $this->_service_type = $value;		}		public function setOn_time($value){ 			 $this->_on_time = $value;		}		public function setCount_cash($value){ 			 $this->_count_cash = $value;		}		public function setPay_cash($value){ 			 $this->_pay_cash = $value;		}		public function setClr_cash($value){ 			 $this->_clr_cash = $value;		}		public function setTitle($value){ 			 $this->_title = $value;		}		public function setSale_status($value){ 			 $this->_sale_status = $value;		}		public function setBuyer_status($value){ 			 $this->_buyer_status = $value;		}		public function setOrder_status($value){ 			 $this->_order_status = $value;		}		public function setBuy_username($value){ 			 $this->_buy_username = $value;		}		public function setBuy_uid($value){ 			 $this->_buy_uid = $value;		}		public function setCost_cash($value){ 			 $this->_cost_cash = $value;		}		public function setCost_credit($value){ 			 $this->_cost_credit = $value;		}		public function setOrder_num($value){ 			 $this->_order_num = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_service_order  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_service_order(){		 		 $data =  array(); 					if(!is_null($this->_order_id)){ 				 $data['order_id']=$this->_order_id;			}			if(!is_null($this->_model_id)){ 				 $data['model_id']=$this->_model_id;			}			if(!is_null($this->_sale_uid)){ 				 $data['sale_uid']=$this->_sale_uid;			}			if(!is_null($this->_sale_username)){ 				 $data['sale_username']=$this->_sale_username;			}			if(!is_null($this->_service_id)){ 				 $data['service_id']=$this->_service_id;			}			if(!is_null($this->_service_type)){ 				 $data['service_type']=$this->_service_type;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if(!is_null($this->_count_cash)){ 				 $data['count_cash']=$this->_count_cash;			}			if(!is_null($this->_pay_cash)){ 				 $data['pay_cash']=$this->_pay_cash;			}			if(!is_null($this->_clr_cash)){ 				 $data['clr_cash']=$this->_clr_cash;			}			if(!is_null($this->_title)){ 				 $data['title']=$this->_title;			}			if(!is_null($this->_sale_status)){ 				 $data['sale_status']=$this->_sale_status;			}			if(!is_null($this->_buyer_status)){ 				 $data['buyer_status']=$this->_buyer_status;			}			if(!is_null($this->_order_status)){ 				 $data['order_status']=$this->_order_status;			}			if(!is_null($this->_buy_username)){ 				 $data['buy_username']=$this->_buy_username;			}			if(!is_null($this->_buy_uid)){ 				 $data['buy_uid']=$this->_buy_uid;			}			if(!is_null($this->_cost_cash)){ 				 $data['cost_cash']=$this->_cost_cash;			}			if(!is_null($this->_cost_credit)){ 				 $data['cost_credit']=$this->_cost_credit;			}			if(!is_null($this->_order_num)){ 				 $data['order_num']=$this->_order_num;			}			 return $this->_order_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_service_order		 * @return int affected_rows		 */		function edit_keke_witkey_service_order(){ 		 		 $data =  array();  					if(!is_null($this->_order_id)){ 				 $data['order_id']=$this->_order_id;			}			if(!is_null($this->_model_id)){ 				 $data['model_id']=$this->_model_id;			}			if(!is_null($this->_sale_uid)){ 				 $data['sale_uid']=$this->_sale_uid;			}			if(!is_null($this->_sale_username)){ 				 $data['sale_username']=$this->_sale_username;			}			if(!is_null($this->_service_id)){ 				 $data['service_id']=$this->_service_id;			}			if(!is_null($this->_service_type)){ 				 $data['service_type']=$this->_service_type;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if(!is_null($this->_count_cash)){ 				 $data['count_cash']=$this->_count_cash;			}			if(!is_null($this->_pay_cash)){ 				 $data['pay_cash']=$this->_pay_cash;			}			if(!is_null($this->_clr_cash)){ 				 $data['clr_cash']=$this->_clr_cash;			}			if(!is_null($this->_title)){ 				 $data['title']=$this->_title;			}			if(!is_null($this->_sale_status)){ 				 $data['sale_status']=$this->_sale_status;			}			if(!is_null($this->_buyer_status)){ 				 $data['buyer_status']=$this->_buyer_status;			}			if(!is_null($this->_order_status)){ 				 $data['order_status']=$this->_order_status;			}			if(!is_null($this->_buy_username)){ 				 $data['buy_username']=$this->_buy_username;			}			if(!is_null($this->_buy_uid)){ 				 $data['buy_uid']=$this->_buy_uid;			}			if(!is_null($this->_cost_cash)){ 				 $data['cost_cash']=$this->_cost_cash;			}			if(!is_null($this->_cost_credit)){ 				 $data['cost_credit']=$this->_cost_credit;			}			if(!is_null($this->_order_num)){ 				 $data['order_num']=$this->_order_num;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('order_id' => $this->_order_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_service_order,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_service_order($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_service_order records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_service_order(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_service_order, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_service_order(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where order_id = $this->_order_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>