<?php
  class Keke_witkey_video_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_v_id;  		 public $_v_title; 		 public $_v_cat; 		 public $_v_status; 		 public $_is_recommend; 		 public $_v_path; 		 public $_dateline; 		 public $_listorder; 		 public $_seo_title; 		 public $_seo_keywords; 		 public $_seo_desc; 		 public $_seo_catname; 		 public $_img; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_video_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_video";		 }	    
	    		public function getV_id(){			 return $this->_v_id ;		}		public function getV_title(){			 return $this->_v_title ;		}		public function getV_cat(){			 return $this->_v_cat ;		}		public function getV_status(){			 return $this->_v_status ;		}		public function getIs_recommend(){			 return $this->_is_recommend ;		}		public function getV_path(){			 return $this->_v_path ;		}		public function getDateline(){			 return $this->_dateline ;		}		public function getListorder(){			 return $this->_listorder ;		}		public function getSeo_title(){			 return $this->_seo_title ;		}		public function getSeo_keywords(){			 return $this->_seo_keywords ;		}		public function getSeo_desc(){			 return $this->_seo_desc ;		}		public function getSeo_catname(){			 return $this->_seo_catname ;		}		public function getImg(){			 return $this->_img ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setV_id($value){ 			 $this->_v_id = $value;		}		public function setV_title($value){ 			 $this->_v_title = $value;		}		public function setV_cat($value){ 			 $this->_v_cat = $value;		}		public function setV_status($value){ 			 $this->_v_status = $value;		}		public function setIs_recommend($value){ 			 $this->_is_recommend = $value;		}		public function setV_path($value){ 			 $this->_v_path = $value;		}		public function setDateline($value){ 			 $this->_dateline = $value;		}		public function setListorder($value){ 			 $this->_listorder = $value;		}		public function setSeo_title($value){ 			 $this->_seo_title = $value;		}		public function setSeo_keywords($value){ 			 $this->_seo_keywords = $value;		}		public function setSeo_desc($value){ 			 $this->_seo_desc = $value;		}		public function setSeo_catname($value){ 			 $this->_seo_catname = $value;		}		public function setImg($value){ 			 $this->_img = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_video  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_video(){		 		 $data =  array(); 					if(!is_null($this->_v_id)){ 				 $data['v_id']=$this->_v_id;			}			if(!is_null($this->_v_title)){ 				 $data['v_title']=$this->_v_title;			}			if(!is_null($this->_v_cat)){ 				 $data['v_cat']=$this->_v_cat;			}			if(!is_null($this->_v_status)){ 				 $data['v_status']=$this->_v_status;			}			if(!is_null($this->_is_recommend)){ 				 $data['is_recommend']=$this->_is_recommend;			}			if(!is_null($this->_v_path)){ 				 $data['v_path']=$this->_v_path;			}			if(!is_null($this->_dateline)){ 				 $data['dateline']=$this->_dateline;			}			if(!is_null($this->_listorder)){ 				 $data['listorder']=$this->_listorder;			}			if(!is_null($this->_seo_title)){ 				 $data['seo_title']=$this->_seo_title;			}			if(!is_null($this->_seo_keywords)){ 				 $data['seo_keywords']=$this->_seo_keywords;			}			if(!is_null($this->_seo_desc)){ 				 $data['seo_desc']=$this->_seo_desc;			}			if(!is_null($this->_seo_catname)){ 				 $data['seo_catname']=$this->_seo_catname;			}			if(!is_null($this->_img)){ 				 $data['img']=$this->_img;			}			 return $this->_v_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_video		 * @return int affected_rows		 */		function edit_keke_witkey_video(){ 		 		 $data =  array();  					if(!is_null($this->_v_id)){ 				 $data['v_id']=$this->_v_id;			}			if(!is_null($this->_v_title)){ 				 $data['v_title']=$this->_v_title;			}			if(!is_null($this->_v_cat)){ 				 $data['v_cat']=$this->_v_cat;			}			if(!is_null($this->_v_status)){ 				 $data['v_status']=$this->_v_status;			}			if(!is_null($this->_is_recommend)){ 				 $data['is_recommend']=$this->_is_recommend;			}			if(!is_null($this->_v_path)){ 				 $data['v_path']=$this->_v_path;			}			if(!is_null($this->_dateline)){ 				 $data['dateline']=$this->_dateline;			}			if(!is_null($this->_listorder)){ 				 $data['listorder']=$this->_listorder;			}			if(!is_null($this->_seo_title)){ 				 $data['seo_title']=$this->_seo_title;			}			if(!is_null($this->_seo_keywords)){ 				 $data['seo_keywords']=$this->_seo_keywords;			}			if(!is_null($this->_seo_desc)){ 				 $data['seo_desc']=$this->_seo_desc;			}			if(!is_null($this->_seo_catname)){ 				 $data['seo_catname']=$this->_seo_catname;			}			if(!is_null($this->_img)){ 				 $data['img']=$this->_img;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('v_id' => $this->_v_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_video,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_video($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_video records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_video(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_video, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_video(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where v_id = $this->_v_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>