<?php
  class Keke_messqueue_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_messageid;  		 public $_messagetype; 		 public $_targetno; 		 public $_title; 		 public $_contents; 		 public $_sendflag; 		 public $_intime; 		 public $_outtime; 		 public $_returncode; 		 public $_sendcount; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_messqueue_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."messqueue";		 }	    
	    		public function getMessageid(){			 return $this->_messageid ;		}		public function getMessagetype(){			 return $this->_messagetype ;		}		public function getTargetno(){			 return $this->_targetno ;		}		public function getTitle(){			 return $this->_title ;		}		public function getContents(){			 return $this->_contents ;		}		public function getSendflag(){			 return $this->_sendflag ;		}		public function getIntime(){			 return $this->_intime ;		}		public function getOuttime(){			 return $this->_outtime ;		}		public function getReturncode(){			 return $this->_returncode ;		}		public function getSendcount(){			 return $this->_sendcount ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setMessageid($value){ 			 $this->_messageid = $value;		}		public function setMessagetype($value){ 			 $this->_messagetype = $value;		}		public function setTargetno($value){ 			 $this->_targetno = $value;		}		public function setTitle($value){ 			 $this->_title = $value;		}		public function setContents($value){ 			 $this->_contents = $value;		}		public function setSendflag($value){ 			 $this->_sendflag = $value;		}		public function setIntime($value){ 			 $this->_intime = $value;		}		public function setOuttime($value){ 			 $this->_outtime = $value;		}		public function setReturncode($value){ 			 $this->_returncode = $value;		}		public function setSendcount($value){ 			 $this->_sendcount = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_messqueue  ,or add new record		 * @return int last_insert_id		 */		function create_keke_messqueue(){		 		 $data =  array(); 					if(!is_null($this->_messageid)){ 				 $data['messageid']=$this->_messageid;			}			if(!is_null($this->_messagetype)){ 				 $data['messagetype']=$this->_messagetype;			}			if(!is_null($this->_targetno)){ 				 $data['targetno']=$this->_targetno;			}			if(!is_null($this->_title)){ 				 $data['title']=$this->_title;			}			if(!is_null($this->_contents)){ 				 $data['contents']=$this->_contents;			}			if(!is_null($this->_sendflag)){ 				 $data['sendflag']=$this->_sendflag;			}			if(!is_null($this->_intime)){ 				 $data['intime']=$this->_intime;			}			if(!is_null($this->_outtime)){ 				 $data['outtime']=$this->_outtime;			}			if(!is_null($this->_returncode)){ 				 $data['returncode']=$this->_returncode;			}			if(!is_null($this->_sendcount)){ 				 $data['sendcount']=$this->_sendcount;			}			 return $this->_messageid = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_messqueue		 * @return int affected_rows		 */		function edit_keke_messqueue(){ 		 		 $data =  array();  					if(!is_null($this->_messageid)){ 				 $data['messageid']=$this->_messageid;			}			if(!is_null($this->_messagetype)){ 				 $data['messagetype']=$this->_messagetype;			}			if(!is_null($this->_targetno)){ 				 $data['targetno']=$this->_targetno;			}			if(!is_null($this->_title)){ 				 $data['title']=$this->_title;			}			if(!is_null($this->_contents)){ 				 $data['contents']=$this->_contents;			}			if(!is_null($this->_sendflag)){ 				 $data['sendflag']=$this->_sendflag;			}			if(!is_null($this->_intime)){ 				 $data['intime']=$this->_intime;			}			if(!is_null($this->_outtime)){ 				 $data['outtime']=$this->_outtime;			}			if(!is_null($this->_returncode)){ 				 $data['returncode']=$this->_returncode;			}			if(!is_null($this->_sendcount)){ 				 $data['sendcount']=$this->_sendcount;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('messageid' => $this->_messageid); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_messqueue,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_messqueue($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_messqueue records,if iset where query by where 		 * @return int count records		 */		function count_keke_messqueue(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_messqueue, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_messqueue(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where messageid = $this->_messageid "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>