<?php
  class Keke_witkey_hire_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_hire_id;  		 public $_uid; 		 public $_username; 		 public $_euid; 		 public $_eusername; 		 public $_price; 		 public $_title; 		 public $_hire_status; 		 public $_open_step; 		 public $_content; 		 public $_buyer_status; 		 public $_seller_status; 		 public $_wish_time; 		 public $_dateline; 		 public $_unique_num; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_hire_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."itkey_hire";		 }	    
	    		public function getHire_id(){			 return $this->_hire_id ;		}		public function getUid(){			 return $this->_uid ;		}		public function getUsername(){			 return $this->_username ;		}		public function getEuid(){			 return $this->_euid ;		}		public function getEusername(){			 return $this->_eusername ;		}		public function getPrice(){			 return $this->_price ;		}		public function getTitle(){			 return $this->_title ;		}		public function getHire_status(){			 return $this->_hire_status ;		}		public function getOpen_step(){			 return $this->_open_step ;		}		public function getContent(){			 return $this->_content ;		}		public function getBuyer_status(){			 return $this->_buyer_status ;		}		public function getSeller_status(){			 return $this->_seller_status ;		}		public function getWish_time(){			 return $this->_wish_time ;		}		public function getDateline(){			 return $this->_dateline ;		}		public function getUnique_num(){			 return $this->_unique_num ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setHire_id($value){ 			 $this->_hire_id = $value;		}		public function setUid($value){ 			 $this->_uid = $value;		}		public function setUsername($value){ 			 $this->_username = $value;		}		public function setEuid($value){ 			 $this->_euid = $value;		}		public function setEusername($value){ 			 $this->_eusername = $value;		}		public function setPrice($value){ 			 $this->_price = $value;		}		public function setTitle($value){ 			 $this->_title = $value;		}		public function setHire_status($value){ 			 $this->_hire_status = $value;		}		public function setOpen_step($value){ 			 $this->_open_step = $value;		}		public function setContent($value){ 			 $this->_content = $value;		}		public function setBuyer_status($value){ 			 $this->_buyer_status = $value;		}		public function setSeller_status($value){ 			 $this->_seller_status = $value;		}		public function setWish_time($value){ 			 $this->_wish_time = $value;		}		public function setDateline($value){ 			 $this->_dateline = $value;		}		public function setUnique_num($value){ 			 $this->_unique_num = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_hire  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_hire(){		 		 $data =  array(); 					if(!is_null($this->_hire_id)){ 				 $data['hire_id']=$this->_hire_id;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_euid)){ 				 $data['euid']=$this->_euid;			}			if(!is_null($this->_eusername)){ 				 $data['eusername']=$this->_eusername;			}			if(!is_null($this->_price)){ 				 $data['price']=$this->_price;			}			if(!is_null($this->_title)){ 				 $data['title']=$this->_title;			}			if(!is_null($this->_hire_status)){ 				 $data['hire_status']=$this->_hire_status;			}			if(!is_null($this->_open_step)){ 				 $data['open_step']=$this->_open_step;			}			if(!is_null($this->_content)){ 				 $data['content']=$this->_content;			}			if(!is_null($this->_buyer_status)){ 				 $data['buyer_status']=$this->_buyer_status;			}			if(!is_null($this->_seller_status)){ 				 $data['seller_status']=$this->_seller_status;			}			if(!is_null($this->_wish_time)){ 				 $data['wish_time']=$this->_wish_time;			}			if(!is_null($this->_dateline)){ 				 $data['dateline']=$this->_dateline;			}			if(!is_null($this->_unique_num)){ 				 $data['unique_num']=$this->_unique_num;			}			 return $this->_hire_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_hire		 * @return int affected_rows		 */		function edit_keke_witkey_hire(){ 		 		 $data =  array();  					if(!is_null($this->_hire_id)){ 				 $data['hire_id']=$this->_hire_id;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_euid)){ 				 $data['euid']=$this->_euid;			}			if(!is_null($this->_eusername)){ 				 $data['eusername']=$this->_eusername;			}			if(!is_null($this->_price)){ 				 $data['price']=$this->_price;			}			if(!is_null($this->_title)){ 				 $data['title']=$this->_title;			}			if(!is_null($this->_hire_status)){ 				 $data['hire_status']=$this->_hire_status;			}			if(!is_null($this->_open_step)){ 				 $data['open_step']=$this->_open_step;			}			if(!is_null($this->_content)){ 				 $data['content']=$this->_content;			}			if(!is_null($this->_buyer_status)){ 				 $data['buyer_status']=$this->_buyer_status;			}			if(!is_null($this->_seller_status)){ 				 $data['seller_status']=$this->_seller_status;			}			if(!is_null($this->_wish_time)){ 				 $data['wish_time']=$this->_wish_time;			}			if(!is_null($this->_dateline)){ 				 $data['dateline']=$this->_dateline;			}			if(!is_null($this->_unique_num)){ 				 $data['unique_num']=$this->_unique_num;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('hire_id' => $this->_hire_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_hire,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_hire($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_hire records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_hire(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_hire, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_hire(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where hire_id = $this->_hire_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>