<?php
  class Keke_witkey_shop_menu_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_menu_id;  		 public $_shop_id; 		 public $_menu_type; 		 public $_menu_1; 		 public $_menu_2; 		 public $_menu_3; 		 public $_menu_4; 		 public $_menu_5; 		 public $_list_order; 		 public $_uid; 		 public $_username; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_shop_menu_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."itkey_shop_menu";		 }	    
	    		public function getMenu_id(){			 return $this->_menu_id ;		}		public function getShop_id(){			 return $this->_shop_id ;		}		public function getMenu_type(){			 return $this->_menu_type ;		}		public function getMenu_1(){			 return $this->_menu_1 ;		}		public function getMenu_2(){			 return $this->_menu_2 ;		}		public function getMenu_3(){			 return $this->_menu_3 ;		}		public function getMenu_4(){			 return $this->_menu_4 ;		}		public function getMenu_5(){			 return $this->_menu_5 ;		}		public function getList_order(){			 return $this->_list_order ;		}		public function getUid(){			 return $this->_uid ;		}		public function getUsername(){			 return $this->_username ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setMenu_id($value){ 			 $this->_menu_id = $value;		}		public function setShop_id($value){ 			 $this->_shop_id = $value;		}		public function setMenu_type($value){ 			 $this->_menu_type = $value;		}		public function setMenu_1($value){ 			 $this->_menu_1 = $value;		}		public function setMenu_2($value){ 			 $this->_menu_2 = $value;		}		public function setMenu_3($value){ 			 $this->_menu_3 = $value;		}		public function setMenu_4($value){ 			 $this->_menu_4 = $value;		}		public function setMenu_5($value){ 			 $this->_menu_5 = $value;		}		public function setList_order($value){ 			 $this->_list_order = $value;		}		public function setUid($value){ 			 $this->_uid = $value;		}		public function setUsername($value){ 			 $this->_username = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_shop_menu  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_shop_menu(){		 		 $data =  array(); 					if(!is_null($this->_menu_id)){ 				 $data['menu_id']=$this->_menu_id;			}			if(!is_null($this->_shop_id)){ 				 $data['shop_id']=$this->_shop_id;			}			if(!is_null($this->_menu_type)){ 				 $data['menu_type']=$this->_menu_type;			}			if(!is_null($this->_menu_1)){ 				 $data['menu_1']=$this->_menu_1;			}			if(!is_null($this->_menu_2)){ 				 $data['menu_2']=$this->_menu_2;			}			if(!is_null($this->_menu_3)){ 				 $data['menu_3']=$this->_menu_3;			}			if(!is_null($this->_menu_4)){ 				 $data['menu_4']=$this->_menu_4;			}			if(!is_null($this->_menu_5)){ 				 $data['menu_5']=$this->_menu_5;			}			if(!is_null($this->_list_order)){ 				 $data['list_order']=$this->_list_order;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			 return $this->_menu_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_shop_menu		 * @return int affected_rows		 */		function edit_keke_witkey_shop_menu(){ 		 		 $data =  array();  					if(!is_null($this->_menu_id)){ 				 $data['menu_id']=$this->_menu_id;			}			if(!is_null($this->_shop_id)){ 				 $data['shop_id']=$this->_shop_id;			}			if(!is_null($this->_menu_type)){ 				 $data['menu_type']=$this->_menu_type;			}			if(!is_null($this->_menu_1)){ 				 $data['menu_1']=$this->_menu_1;			}			if(!is_null($this->_menu_2)){ 				 $data['menu_2']=$this->_menu_2;			}			if(!is_null($this->_menu_3)){ 				 $data['menu_3']=$this->_menu_3;			}			if(!is_null($this->_menu_4)){ 				 $data['menu_4']=$this->_menu_4;			}			if(!is_null($this->_menu_5)){ 				 $data['menu_5']=$this->_menu_5;			}			if(!is_null($this->_list_order)){ 				 $data['list_order']=$this->_list_order;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('menu_id' => $this->_menu_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_shop_menu,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_shop_menu($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_shop_menu records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_shop_menu(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_shop_menu, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_shop_menu(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where menu_id = $this->_menu_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>