<?php
  class Keke_witkey_prom_style_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_s_id;  		 public $_s_type; 		 public $_s_title; 		 public $_s_url; 		 public $_s_img1; 		 public $_s_img2; 		 public $_s_img3; 		 public $_s_img4; 		 public $_s_img5; 		 public $_s_img6; 		 public $_s_img7; 		 public $_s_img8; 		 public $_on_time; 		 public $_s_status; 		 public $_s_recommend; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_prom_style_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_prom_style";		 }	    
	    		public function getS_id(){			 return $this->_s_id ;		}		public function getS_type(){			 return $this->_s_type ;		}		public function getS_title(){			 return $this->_s_title ;		}		public function getS_url(){			 return $this->_s_url ;		}		public function getS_img1(){			 return $this->_s_img1 ;		}		public function getS_img2(){			 return $this->_s_img2 ;		}		public function getS_img3(){			 return $this->_s_img3 ;		}		public function getS_img4(){			 return $this->_s_img4 ;		}		public function getS_img5(){			 return $this->_s_img5 ;		}		public function getS_img6(){			 return $this->_s_img6 ;		}		public function getS_img7(){			 return $this->_s_img7 ;		}		public function getS_img8(){			 return $this->_s_img8 ;		}		public function getOn_time(){			 return $this->_on_time ;		}		public function getS_status(){			 return $this->_s_status ;		}		public function getS_recommend(){			 return $this->_s_recommend ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setS_id($value){ 			 $this->_s_id = $value;		}		public function setS_type($value){ 			 $this->_s_type = $value;		}		public function setS_title($value){ 			 $this->_s_title = $value;		}		public function setS_url($value){ 			 $this->_s_url = $value;		}		public function setS_img1($value){ 			 $this->_s_img1 = $value;		}		public function setS_img2($value){ 			 $this->_s_img2 = $value;		}		public function setS_img3($value){ 			 $this->_s_img3 = $value;		}		public function setS_img4($value){ 			 $this->_s_img4 = $value;		}		public function setS_img5($value){ 			 $this->_s_img5 = $value;		}		public function setS_img6($value){ 			 $this->_s_img6 = $value;		}		public function setS_img7($value){ 			 $this->_s_img7 = $value;		}		public function setS_img8($value){ 			 $this->_s_img8 = $value;		}		public function setOn_time($value){ 			 $this->_on_time = $value;		}		public function setS_status($value){ 			 $this->_s_status = $value;		}		public function setS_recommend($value){ 			 $this->_s_recommend = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_prom_style  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_prom_style(){		 		 $data =  array(); 					if(!is_null($this->_s_id)){ 				 $data['s_id']=$this->_s_id;			}			if(!is_null($this->_s_type)){ 				 $data['s_type']=$this->_s_type;			}			if(!is_null($this->_s_title)){ 				 $data['s_title']=$this->_s_title;			}			if(!is_null($this->_s_url)){ 				 $data['s_url']=$this->_s_url;			}			if(!is_null($this->_s_img1)){ 				 $data['s_img1']=$this->_s_img1;			}			if(!is_null($this->_s_img2)){ 				 $data['s_img2']=$this->_s_img2;			}			if(!is_null($this->_s_img3)){ 				 $data['s_img3']=$this->_s_img3;			}			if(!is_null($this->_s_img4)){ 				 $data['s_img4']=$this->_s_img4;			}			if(!is_null($this->_s_img5)){ 				 $data['s_img5']=$this->_s_img5;			}			if(!is_null($this->_s_img6)){ 				 $data['s_img6']=$this->_s_img6;			}			if(!is_null($this->_s_img7)){ 				 $data['s_img7']=$this->_s_img7;			}			if(!is_null($this->_s_img8)){ 				 $data['s_img8']=$this->_s_img8;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if(!is_null($this->_s_status)){ 				 $data['s_status']=$this->_s_status;			}			if(!is_null($this->_s_recommend)){ 				 $data['s_recommend']=$this->_s_recommend;			}			 return $this->_s_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_prom_style		 * @return int affected_rows		 */		function edit_keke_witkey_prom_style(){ 		 		 $data =  array();  					if(!is_null($this->_s_id)){ 				 $data['s_id']=$this->_s_id;			}			if(!is_null($this->_s_type)){ 				 $data['s_type']=$this->_s_type;			}			if(!is_null($this->_s_title)){ 				 $data['s_title']=$this->_s_title;			}			if(!is_null($this->_s_url)){ 				 $data['s_url']=$this->_s_url;			}			if(!is_null($this->_s_img1)){ 				 $data['s_img1']=$this->_s_img1;			}			if(!is_null($this->_s_img2)){ 				 $data['s_img2']=$this->_s_img2;			}			if(!is_null($this->_s_img3)){ 				 $data['s_img3']=$this->_s_img3;			}			if(!is_null($this->_s_img4)){ 				 $data['s_img4']=$this->_s_img4;			}			if(!is_null($this->_s_img5)){ 				 $data['s_img5']=$this->_s_img5;			}			if(!is_null($this->_s_img6)){ 				 $data['s_img6']=$this->_s_img6;			}			if(!is_null($this->_s_img7)){ 				 $data['s_img7']=$this->_s_img7;			}			if(!is_null($this->_s_img8)){ 				 $data['s_img8']=$this->_s_img8;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if(!is_null($this->_s_status)){ 				 $data['s_status']=$this->_s_status;			}			if(!is_null($this->_s_recommend)){ 				 $data['s_recommend']=$this->_s_recommend;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('s_id' => $this->_s_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_prom_style,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_prom_style($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_prom_style records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_prom_style(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_prom_style, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_prom_style(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where s_id = $this->_s_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>