<?php
  class Keke_witkey_shop_ad_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_ad_id;  		 public $_uid; 		 public $_username; 		 public $_shop_id; 		 public $_shop_name; 		 public $_ad_title; 		 public $_ad_type; 		 public $_listorder; 		 public $_ad_pic; 		 public $_ad_url; 		 public $_on_time; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_shop_ad_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_shop_ad";		 }	    
	    		public function getAd_id(){			 return $this->_ad_id ;		}		public function getUid(){			 return $this->_uid ;		}		public function getUsername(){			 return $this->_username ;		}		public function getShop_id(){			 return $this->_shop_id ;		}		public function getShop_name(){			 return $this->_shop_name ;		}		public function getAd_title(){			 return $this->_ad_title ;		}		public function getAd_type(){			 return $this->_ad_type ;		}		public function getListorder(){			 return $this->_listorder ;		}		public function getAd_pic(){			 return $this->_ad_pic ;		}		public function getAd_url(){			 return $this->_ad_url ;		}		public function getOn_time(){			 return $this->_on_time ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setAd_id($value){ 			 $this->_ad_id = $value;		}		public function setUid($value){ 			 $this->_uid = $value;		}		public function setUsername($value){ 			 $this->_username = $value;		}		public function setShop_id($value){ 			 $this->_shop_id = $value;		}		public function setShop_name($value){ 			 $this->_shop_name = $value;		}		public function setAd_title($value){ 			 $this->_ad_title = $value;		}		public function setAd_type($value){ 			 $this->_ad_type = $value;		}		public function setListorder($value){ 			 $this->_listorder = $value;		}		public function setAd_pic($value){ 			 $this->_ad_pic = $value;		}		public function setAd_url($value){ 			 $this->_ad_url = $value;		}		public function setOn_time($value){ 			 $this->_on_time = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_shop_ad  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_shop_ad(){		 		 $data =  array(); 					if(!is_null($this->_ad_id)){ 				 $data['ad_id']=$this->_ad_id;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_shop_id)){ 				 $data['shop_id']=$this->_shop_id;			}			if(!is_null($this->_shop_name)){ 				 $data['shop_name']=$this->_shop_name;			}			if(!is_null($this->_ad_title)){ 				 $data['ad_title']=$this->_ad_title;			}			if(!is_null($this->_ad_type)){ 				 $data['ad_type']=$this->_ad_type;			}			if(!is_null($this->_listorder)){ 				 $data['listorder']=$this->_listorder;			}			if(!is_null($this->_ad_pic)){ 				 $data['ad_pic']=$this->_ad_pic;			}			if(!is_null($this->_ad_url)){ 				 $data['ad_url']=$this->_ad_url;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			 return $this->_ad_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_shop_ad		 * @return int affected_rows		 */		function edit_keke_witkey_shop_ad(){ 		 		 $data =  array();  					if(!is_null($this->_ad_id)){ 				 $data['ad_id']=$this->_ad_id;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_shop_id)){ 				 $data['shop_id']=$this->_shop_id;			}			if(!is_null($this->_shop_name)){ 				 $data['shop_name']=$this->_shop_name;			}			if(!is_null($this->_ad_title)){ 				 $data['ad_title']=$this->_ad_title;			}			if(!is_null($this->_ad_type)){ 				 $data['ad_type']=$this->_ad_type;			}			if(!is_null($this->_listorder)){ 				 $data['listorder']=$this->_listorder;			}			if(!is_null($this->_ad_pic)){ 				 $data['ad_pic']=$this->_ad_pic;			}			if(!is_null($this->_ad_url)){ 				 $data['ad_url']=$this->_ad_url;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('ad_id' => $this->_ad_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_shop_ad,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_shop_ad($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_shop_ad records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_shop_ad(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_shop_ad, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_shop_ad(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where ad_id = $this->_ad_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>