<?php
  class Keke_witkey_invoice_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_iv_id;  		 public $_task_id; 		 public $_task_title; 		 public $_model_id; 		 public $_uid; 		 public $_username; 		 public $_iv_client; 		 public $_iv_reason; 		 public $_iv_documenttype; 		 public $_iv_documentnum; 		 public $_iv_contact; 		 public $_iv_province; 		 public $_iv_city; 		 public $_iv_add; 		 public $_iv_zipcode; 		 public $_iv_phone; 		 public $_iv_price; 		 public $_iv_taxes; 
		 public $_iv_item_cash; 		 public $_iv_taxes_status; 		 public $_iv_fee; 		 public $_iv_status; 		 public $_iv_datetime; 		 public $_iv_tm_status; 		 public $_iv_checktime; 		 public $_iv_checkuid; 		 public $_iv_checkusername; 		 public $_iv_applicount; 		 public $_transport_type; 		 public $_transport_orderid; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_invoice_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_invoice";		 }	    
	    		public function getIv_id(){			 return $this->_iv_id ;		}		public function getTask_id(){			 return $this->_task_id ;		}		public function getTask_title(){			 return $this->_task_title ;		}		public function getModel_id(){			 return $this->_model_id ;		}		public function getUid(){			 return $this->_uid ;		}		public function getUsername(){			 return $this->_username ;		}		public function getIv_client(){			 return $this->_iv_client ;		}		public function getIv_reason(){			 return $this->_iv_reason ;		}		public function getIv_documenttype(){			 return $this->_iv_documenttype ;		}		public function getIv_documentnum(){			 return $this->_iv_documentnum ;		}		public function getIv_contact(){			 return $this->_iv_contact ;		}		public function getIv_province(){			 return $this->_iv_province ;		}		public function getIv_city(){			 return $this->_iv_city ;		}		public function getIv_add(){			 return $this->_iv_add ;		}		public function getIv_zipcode(){			 return $this->_iv_zipcode ;		}		public function getIv_phone(){			 return $this->_iv_phone ;		}		public function getIv_price(){			 return $this->_iv_price ;		}
		public function getIv_item_cash(){
			 return $this->_iv_item_cash ;
		}		public function getIv_taxes(){			 return $this->_iv_taxes ;		}		public function getIv_taxes_status(){			 return $this->_iv_taxes_status ;		}		public function getIv_fee(){			 return $this->_iv_fee ;		}		public function getIv_status(){			 return $this->_iv_status ;		}		public function getIv_datetime(){			 return $this->_iv_datetime ;		}		public function getIv_tm_status(){			 return $this->_iv_tm_status ;		}		public function getIv_checktime(){			 return $this->_iv_checktime ;		}		public function getIv_checkuid(){			 return $this->_iv_checkuid ;		}		public function getIv_checkusername(){			 return $this->_iv_checkusername ;		}		public function getIv_applicount(){			 return $this->_iv_applicount ;		}		public function getTransport_type(){			 return $this->_transport_type ;		}		public function getTransport_orderid(){			 return $this->_transport_orderid ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setIv_id($value){ 			 $this->_iv_id = $value;		}		public function setTask_id($value){ 			 $this->_task_id = $value;		}		public function setTask_title($value){ 			 $this->_task_title = $value;		}		public function setModel_id($value){ 			 $this->_model_id = $value;		}		public function setUid($value){ 			 $this->_uid = $value;		}		public function setUsername($value){ 			 $this->_username = $value;		}		public function setIv_client($value){ 			 $this->_iv_client = $value;		}		public function setIv_reason($value){ 			 $this->_iv_reason = $value;		}		public function setIv_documenttype($value){ 			 $this->_iv_documenttype = $value;		}		public function setIv_documentnum($value){ 			 $this->_iv_documentnum = $value;		}		public function setIv_contact($value){ 			 $this->_iv_contact = $value;		}		public function setIv_province($value){ 			 $this->_iv_province = $value;		}		public function setIv_city($value){ 			 $this->_iv_city = $value;		}		public function setIv_add($value){ 			 $this->_iv_add = $value;		}		public function setIv_zipcode($value){ 			 $this->_iv_zipcode = $value;		}		public function setIv_phone($value){ 			 $this->_iv_phone = $value;		}		public function setIv_price($value){ 			 $this->_iv_price = $value;		}
		public function setIv_item_cash($value){ 
			 $this->_iv_item_cash = $value;
		}		public function setIv_taxes($value){ 			 $this->_iv_taxes = $value;		}		public function setIv_taxes_status($value){ 			 $this->_iv_taxes_status = $value;		}		public function setIv_fee($value){ 			 $this->_iv_fee = $value;		}		public function setIv_status($value){ 			 $this->_iv_status = $value;		}		public function setIv_datetime($value){ 			 $this->_iv_datetime = $value;		}		public function setIv_tm_status($value){ 			 $this->_iv_tm_status = $value;		}		public function setIv_checktime($value){ 			 $this->_iv_checktime = $value;		}		public function setIv_checkuid($value){ 			 $this->_iv_checkuid = $value;		}		public function setIv_checkusername($value){ 			 $this->_iv_checkusername = $value;		}		public function setIv_applicount($value){ 			 $this->_iv_applicount = $value;		}		public function setTransport_type($value){ 			 $this->_transport_type = $value;		}		public function setTransport_orderid($value){ 			 $this->_transport_orderid = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_invoice  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_invoice(){		 		 $data =  array(); 					if(!is_null($this->_iv_id)){ 				 $data['iv_id']=$this->_iv_id;			}			if(!is_null($this->_task_id)){ 				 $data['task_id']=$this->_task_id;			}			if(!is_null($this->_task_title)){ 				 $data['task_title']=$this->_task_title;			}			if(!is_null($this->_model_id)){ 				 $data['model_id']=$this->_model_id;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_iv_client)){ 				 $data['iv_client']=$this->_iv_client;			}			if(!is_null($this->_iv_reason)){ 				 $data['iv_reason']=$this->_iv_reason;			}			if(!is_null($this->_iv_documenttype)){ 				 $data['iv_documenttype']=$this->_iv_documenttype;			}			if(!is_null($this->_iv_documentnum)){ 				 $data['iv_documentnum']=$this->_iv_documentnum;			}			if(!is_null($this->_iv_contact)){ 				 $data['iv_contact']=$this->_iv_contact;			}			if(!is_null($this->_iv_province)){ 				 $data['iv_province']=$this->_iv_province;			}			if(!is_null($this->_iv_city)){ 				 $data['iv_city']=$this->_iv_city;			}			if(!is_null($this->_iv_add)){ 				 $data['iv_add']=$this->_iv_add;			}			if(!is_null($this->_iv_zipcode)){ 				 $data['iv_zipcode']=$this->_iv_zipcode;			}			if(!is_null($this->_iv_phone)){ 				 $data['iv_phone']=$this->_iv_phone;			}			if(!is_null($this->_iv_price)){ 				 $data['iv_price']=$this->_iv_price;			}
			if(!is_null($this->_iv_item_cash)){ 
				 $data['iv_item_cash']=$this->_iv_item_cash;
			}			if(!is_null($this->_iv_taxes)){ 				 $data['iv_taxes']=$this->_iv_taxes;			}			if(!is_null($this->_iv_taxes_status)){ 				 $data['iv_taxes_status']=$this->_iv_taxes_status;			}			if(!is_null($this->_iv_fee)){ 				 $data['iv_fee']=$this->_iv_fee;			}			if(!is_null($this->_iv_status)){ 				 $data['iv_status']=$this->_iv_status;			}			if(!is_null($this->_iv_datetime)){ 				 $data['iv_datetime']=$this->_iv_datetime;			}			if(!is_null($this->_iv_tm_status)){ 				 $data['iv_tm_status']=$this->_iv_tm_status;			}			if(!is_null($this->_iv_checktime)){ 				 $data['iv_checktime']=$this->_iv_checktime;			}			if(!is_null($this->_iv_checkuid)){ 				 $data['iv_checkuid']=$this->_iv_checkuid;			}			if(!is_null($this->_iv_checkusername)){ 				 $data['iv_checkusername']=$this->_iv_checkusername;			}			if(!is_null($this->_iv_applicount)){ 				 $data['iv_applicount']=$this->_iv_applicount;			}			if(!is_null($this->_transport_type)){ 				 $data['transport_type']=$this->_transport_type;			}			if(!is_null($this->_transport_orderid)){ 				 $data['transport_orderid']=$this->_transport_orderid;			}			 return $this->_iv_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_invoice		 * @return int affected_rows		 */		function edit_keke_witkey_invoice(){ 		 		 $data =  array();  					if(!is_null($this->_iv_id)){ 				 $data['iv_id']=$this->_iv_id;			}			if(!is_null($this->_task_id)){ 				 $data['task_id']=$this->_task_id;			}			if(!is_null($this->_task_title)){ 				 $data['task_title']=$this->_task_title;			}			if(!is_null($this->_model_id)){ 				 $data['model_id']=$this->_model_id;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_iv_client)){ 				 $data['iv_client']=$this->_iv_client;			}			if(!is_null($this->_iv_reason)){ 				 $data['iv_reason']=$this->_iv_reason;			}			if(!is_null($this->_iv_documenttype)){ 				 $data['iv_documenttype']=$this->_iv_documenttype;			}			if(!is_null($this->_iv_documentnum)){ 				 $data['iv_documentnum']=$this->_iv_documentnum;			}			if(!is_null($this->_iv_contact)){ 				 $data['iv_contact']=$this->_iv_contact;			}			if(!is_null($this->_iv_province)){ 				 $data['iv_province']=$this->_iv_province;			}			if(!is_null($this->_iv_city)){ 				 $data['iv_city']=$this->_iv_city;			}			if(!is_null($this->_iv_add)){ 				 $data['iv_add']=$this->_iv_add;			}			if(!is_null($this->_iv_zipcode)){ 				 $data['iv_zipcode']=$this->_iv_zipcode;			}			if(!is_null($this->_iv_phone)){ 				 $data['iv_phone']=$this->_iv_phone;			}			if(!is_null($this->_iv_price)){ 				 $data['iv_price']=$this->_iv_price;			}
			if(!is_null($this->_iv_item_cash)){ 
				 $data['iv_item_cash']=$this->_iv_item_cash;
			}			if(!is_null($this->_iv_taxes)){ 				 $data['iv_taxes']=$this->_iv_taxes;			}			if(!is_null($this->_iv_taxes_status)){ 				 $data['iv_taxes_status']=$this->_iv_taxes_status;			}			if(!is_null($this->_iv_fee)){ 				 $data['iv_fee']=$this->_iv_fee;			}			if(!is_null($this->_iv_status)){ 				 $data['iv_status']=$this->_iv_status;			}			if(!is_null($this->_iv_datetime)){ 				 $data['iv_datetime']=$this->_iv_datetime;			}			if(!is_null($this->_iv_tm_status)){ 				 $data['iv_tm_status']=$this->_iv_tm_status;			}			if(!is_null($this->_iv_checktime)){ 				 $data['iv_checktime']=$this->_iv_checktime;			}			if(!is_null($this->_iv_checkuid)){ 				 $data['iv_checkuid']=$this->_iv_checkuid;			}			if(!is_null($this->_iv_checkusername)){ 				 $data['iv_checkusername']=$this->_iv_checkusername;			}			if(!is_null($this->_iv_applicount)){ 				 $data['iv_applicount']=$this->_iv_applicount;			}			if(!is_null($this->_transport_type)){ 				 $data['transport_type']=$this->_transport_type;			}			if(!is_null($this->_transport_orderid)){ 				 $data['transport_orderid']=$this->_transport_orderid;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('iv_id' => $this->_iv_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_invoice,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_invoice($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_invoice records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_invoice(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_invoice, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_invoice(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where iv_id = $this->_iv_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>